---
- name: Установка и настройка Filebeat для сбора логов Nginx
  hosts: web_servers
  become: yes
  vars:
    filebeat_deb_path: "/home/zorg/filebeat-8.15.1-amd64.deb"
    filebeat_dest: "/tmp/filebeat.deb"
    elasticsearch_host: "http://192.168.20.9:9200"
    kibana_host: "http://192.168.10.36:5601"

  tasks:
    - name: Установить зависимости
      apt:
        name:
          - curl
          - nginx
        state: present
        update_cache: yes

    - name: Убедиться, что логи Nginx существуют
      file:
        path: "{{ item }}"
        state: touch
        owner: root
        group: adm
        mode: '0644'
      loop:
        - /var/log/nginx/access.log
        - /var/log/nginx/error.log

    - name: Скопировать deb-файл Filebeat
      copy:
        src: "{{ filebeat_deb_path }}"
        dest: "{{ filebeat_dest }}"
        mode: '0644'

    - name: Установить Filebeat
      apt:
        deb: "{{ filebeat_dest }}"

    - name: Настроить filebeat.yml
      copy:
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'
        content: |
          filebeat.inputs:
            - type: log
              enabled: true
              paths:
                - /var/log/nginx/access.log
              fields:
                service: nginx
                log_type: access
              fields_under_root: true

            - type: log
              enabled: true
              paths:
                - /var/log/nginx/error.log
              fields:
                service: nginx
                log_type: error
              fields_under_root: true

          output.elasticsearch:
            hosts: ["{{ elasticsearch_host }}"]

          setup.kibana:
            host: "{{ kibana_host }}"

          logging:
            level: info
            to_files: true
            files:
              path: /var/log/filebeat
              name: filebeat.log
              keepfiles: 7
              permissions: 0644

    - name: Создать директорию логов Filebeat
      file:
        path: /var/log/filebeat
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Удалить filebeat.keystore если он мешает
      file:
        path: /var/lib/filebeat/filebeat.keystore
        state: absent

    - name: Включить и запустить Filebeat
      systemd:
        name: filebeat
        enabled: yes
        state: restarted