---
- name: Установка и настройка Kibana (из .deb)
  hosts: kibana_host
  become: yes
  vars:
    
    elasticsearch_ip: "{{ hostvars['elasticsearch_host']['ansible_host'] }}"
    
    kibana_local_deb_path: "/home/zorg/kibana-8.15.1-amd64.deb" 
    kibana_deb_name: "kibana-8.15.1-amd64.deb" # <-- Обновлено
    kibana_version: "8.15.1" # <-- Обновлено
    kibana_user: "kibana"
    kibana_group: "kibana"
  tasks:
    
    - name: Установить зависимости
      apt:
        name:
          - curl
          - apt-transport-https # Может потребоваться для https apt репозиториев
        state: present
        update_cache: yes

    - name: Скопировать .deb файл Kibana на удаленный хост
      copy:
        src: "{{ kibana_local_deb_path }}" # <-- Путь к .deb файлу
        dest: "/tmp/{{ kibana_deb_name }}" # <-- Копируем в /tmp
        owner: root
        group: root
        mode: '0644'

    - name: Установить Kibana из .deb файла
      apt:
        deb: "/tmp/{{ kibana_deb_name }}" 
      
    - name: Убедиться, что группа kibana существует
      group:
        name: "{{ kibana_group }}"
        state: present
        system: yes

    - name: Убедиться, что пользователь kibana существует
      user:
        name: "{{ kibana_user }}"
        group: "{{ kibana_group }}"
        system: yes
        shell: /bin/false
        home: /usr/share/kibana 
        create_home: no
        comment: "Kibana service user"

    - name: Настроить Kibana (server.host)
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#server.host:'
        line: "server.host: \"0.0.0.0\"" 
        backup: yes

    - name: Настроить Kibana 
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#elasticsearch.hosts:'
        line: "elasticsearch.hosts: [\"http://{{ elasticsearch_ip }}:9200\"]" 
        backup: yes

     - name: Удалить или закомментировать logging.dest из kibana.yml
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^\s*logging\.dest\s*:'
        line: "# logging.dest: /var/log/kibana/kibana.log # Закомментировано, так как не поддерживается"
        backup: yes
        firstmatch: yes
      
    - name: Создать или обновить unit-файл systemd для Kibana (для .deb)
      copy:
        content: |
          [Unit]
          Description=Kibana
          Documentation=https://www.elastic.co/guide/en/kibana/current/index.html
          Wants=network-online.target
          After=network-online.target

          [Service]
          Type=simple
          User={{ kibana_user }}
          Group={{ kibana_group }}
          Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"

          ExecStart=/usr/share/kibana/bin/kibana --config /etc/kibana/kibana.yml
          # ----------------------------------------------------

          
          UMask=0022

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/kibana.service # Перезаписываем установленный .deb
        owner: root
        group: root
        mode: '0644'
      notify:
        - Перезагрузить systemd
        - Включить и запустить Kibana

  handlers:
    - name: Перезагрузить systemd
      systemd:
        daemon_reload: yes

    - name: Включить и запустить Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started

    - name: Перезапустить Kibana
      systemd:
        name: kibana
        state: restarted