---
- name: Установка и настройка Zabbix Agent
  hosts: web_servers:elasticsearch:kibana:bastion # Все ВМ, кроме zabbix_server
  become: yes
  vars:
    # Получаем IP Zabbix сервера из inventory
    zabbix_server_ip: "{{ hostvars['zabbix_server_host']['ansible_host'] }}"
    zabbix_version: "6.0"
    zabbix_repo_codename: "noble"
  tasks:
    - name: Обновить список пакетов
      apt:
        update_cache: yes
      
    - name: Установить ключ репозитория Zabbix
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present
      
    - name: Добавить репозиторий Zabbix (Ubuntu)
      apt_repository:
        repo: "deb [arch=amd64] https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ zabbix_repo_codename }} main"
        state: present
        filename: zabbix
        
    - name: Обновить список пакетов после добавления репозитория Zabbix
      apt:
        update_cache: yes

    - name: Установить Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Настроить Zabbix Agent (Server)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        backup: yes

    - name: Настроить Zabbix Agent (ServerActive)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        backup: yes

    - name: Настроить имя хоста агента
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        backup: yes

    - name: Перезапустить и включить Zabbix Agent
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes